### ISSUE TITLE
Header does not match it's checksum for

### ISSUE THREAD

**Issue by boatbreakers** [ovidiul/XCloner-Wordpress#2]
After a successful backup, when I click on the link to List Backup Content and it displays the following message "Header does not match it's checksum for". 

I have downloaded the .tgz file that was generated and tried to extract it using WinZip which also generated a similar error. (screenshots attached)

![winzip-error](https://cloud.githubusercontent.com/assets/13378789/23359302/8f03bcf2-fcdd-11e6-9f7f-5d95ebc7c874.jpg)

![error-message](https://cloud.githubusercontent.com/assets/13378789/23359226/30c980a4-fcdd-11e6-88a0-67cd710265a0.jpg)

**Comment by ovidiul** [comment]
Could you attach here the XCloner log output or contact me here http://www.thinkovi.com/contact/ to email it? The file is located in wp-content/backups/ folder and it's in format xcloner_main_xxxxx.log

That error usually means the file that was written first to the backup is in incorrect size

**Comment by ovidiul** [comment]
I was able to download your archive, it might be best to hide your backup archive name when posting a public screenshot, i was able to open it and it seemed fine

So the issue seems not to be at the backup generate part, but first it could be the web download, if you try and download the backup through a ftp client, are you able to open it?

 And second, the listing backup content, it's weird as it's working here, are you still having issues there?

![screen shot 2017-02-27 at 15 53 32](https://cloud.githubusercontent.com/assets/537751/23363842/466271b4-fd05-11e6-8b5f-a234adfd40d3.png)
![screen shot 2017-02-27 at 15 53 41](https://cloud.githubusercontent.com/assets/537751/23363844/48678dd2-fd05-11e6-84fd-f2534a8daadc.png)

**Comment by ovidiul** [comment]
I did find an issue with the web download from Manage Backups section and posted a fix here https://github.com/ovidiul/XCloner-Wordpress/commit/603f3aee11e1da5ddbc96188531ef2d498e29c37 , please test and see if you still have issues, you can simply reinstall XCloner from the Wordpress plugins directory

**Comment by ovidiul** [comment]
After further debugging, i've found the source of the issue, i suggest to reinstall the XCloner package to get the latest patched code and try to generate a new backup.

Here is the related commit https://github.com/ovidiul/XCloner-Wordpress/commit/380dba5ce1e9b32526b2805ecb3ab76a312a2fbb

Please let me know if you have further issue.

**Comment by boatbreakers** [comment]
Thanks for your help so far.

I have updated and done another backup, all appears to work fine now in WordPress. The backup process was a lot faster and I can list the backup content with no problems. I downloaded a backup file through FTP and tried extracting it, but I still get the same errors on a Windows PC. I tried using some different software and it gave me this error message (attached).

I have e-mailed you the log file that was generated by this new backup per your previous request.

Many thanks.

![unzip-error](https://cloud.githubusercontent.com/assets/13378789/23402667/7d575f64-fda4-11e6-899d-b406c9a6395c.jpg)

**Comment by ovidiul** [comment]
Thanks for the log, i do no see any errors there related to XCloner backup process

Can you try and use 7zip or similar to extract the backup archive? I do use 7zip and Unarchiver on OSX as well as the TAR linux utility and none complain about the generated archives. I've tested your new archive and it extracts fine here, so i wonder whether this is an issue from winzip, i will check this further on a PC

Also, try setting the compression to zero and see if the uncompressed backup archive are better

**Comment by boatbreakers** [comment]
It was 7zip that gave me that error so it could be a windows issue maybe? I will try an uncompressed backup and get back to you.

Many thanks.

**Comment by ovidiul** [comment]
Please check this here https://github.com/mcmilk/7-Zip-zstd/issues/7 , it could be an issue from 7zip indeed. As a note, XCloner does add 2 blocks of 512 bytes at the end of the backup archive to close it, maybe that's why 7zip complains. 

From what i read, that is just a notice message and the archive files should have been extracted even so...

**Comment by ovidiul** [comment]
Seems i have found the issue and 7zip now doesn't complain anymore, please reinstall XCloner with the latest version and generate a new backup, then try to open it with your local 7zip and let me know if you find further issues

**Comment by boatbreakers** [comment]
Thanks very much for your help, everything is working fine now.

**Comment by ovidiul** [comment]
Thanks for the update, i will close this issue for now.
